import { CompanyProspect, PersonProspect } from "@/types/apolla";

export const peopleProspects: PersonProspect[] = [
  {
    name: "Avi Green",
    title: "CFO",
    location: "United Oil & Gas Corp.",
    email: "agree@1auog.com",
  },
  {
    name: "Siddartha Nedaerk",
    title: "-",
    location: "San Francisco, CA",
    email: "si@1anedaerk.com",
  },
  {
    name: "Sara Smith",
    title: "Director of Engineering",
    location: "San Francisco, CA",
    email: "sar@1agmail.com",
  },
  {
    name: "Brice Swyre",
    title: "SVP, Procurement",
    location: "New York, NY",
    email: "ros@1aedge.com",
  },
  {
    name: "Marjy Marge",
    title: "CFO",
    location: "Austin, TX",
    email: "sea@1aedge.com",
  },
  {
    name: "Yancy Tear",
    title: "VP, Facilities",
    location: "Portland, Oregon",
    email: "jroge@1aburlington.com",
  },
  {
    name: "Irma Vasilik",
    title: "Editor",
    location: "New York, NY",
    email: "irm@1anytimes.com",
  },
  {
    name: "Meghann Durtnal",
    title: "Staff Accountant IV",
    location: "Tucson, AZ",
    email: "ajame@1auog.com",
  },
  {
    name: "Dorothy Durtnal",
    title: "Staff Accountant IV",
    location: "Tucson, AZ",
    email: "do@1adurtnal.com",
  },
  {
    name: "Sammy Seston",
    title: "Accountant I",
    location: "Mountain View, CA",
    email: "tryple@1auog.com",
  },
  {
    name: "Lesya Tinhim",
    title: "Safety Technician IV",
    location: "Singapore, Singapore",
    email: "ibol@1auog.com",
  },
  {
    name: "Zaneta Tewkesbury",
    title: "VP Marketing",
    location: "Chicago, IL",
    email: "za@1atewk.com",
  },
  {
    name: "Nyssa Barrera",
    title: "Marketing Manager",
    location: "Chicago, IL",
    email: "lore@1aoutlook.net",
  },
  {
    name: "Andy Tipple",
    title: "Librarian",
    location: "Gateshead, Tyne and Wear NE26, UK",
    email: "ason@1auog.com",
  },
  {
    name: "Sophi Biles",
    title: "Recruiting Manager",
    location: "Chicago, IL",
    email: "spavlov@1auog.com",
  },
  {
    name: "Florida Garces",
    title: "Web Developer IV",
    location: "Chicago, IL",
    email: "bond_joh@1agrandhotels.com",
  },
  {
    name: "Maribeth Popping",
    title: "Analyst Programmer",
    location: "Mountain View, CA",
    email: "pa@1apyramid.net",
  },
  {
    name: "Moritz Dryburgh",
    title: "Dental Hygienist",
    location: "Singapore, Singapore",
    email: "efran@1agenepoint.com",
  },
  {
    name: "Reid Semiras",
    title: "Teacher",
    location: "Singapore, Singapore",
    email: "asong@1auog.com",
  },
];

export const companyProspects: CompanyProspect[] = [
  {
    name: "Gordian Knot Technologies, Inc.",
    industry: "COMPUTER_SOFTWARE",
    website: "gkti.com",
    numOfEmployees: 0,
    phone: "+1 403-253-9409",
  },
  {
    name: "MEGA International",
    industry: "COMPUTER_SOFTWARE",
    website: "mega.com",
    numOfEmployees: 1000,
    phone: "-",
  },
  {
    name: "PDOA",
    industry: "HOSPITAL_HEALTH_CARE",
    website: "pdoa.com",
    numOfEmployees: 50,
    phone: "8436626233",
  },
  {
    name: "Nmgi",
    industry: "COMPUTER_SOFTWARE",
    website: "NMGI.COM",
    numOfEmployees: 50,
    phone: "+1 620-664-6000",
  },
  {
    name: "United Oil & Gas, UK",
    industry: "Energy",
    website: "http://www.uos.com",
    numOfEmployees: 24000,
    phone: "+44 191 4956203",
  },
  {
    name: "United Oil & Gas, Singapore",
    industry: "Energy",
    website: "http://www.uos.com.sg",
    numOfEmployees: 3000,
    phone: "(650) 450-8810",
  },
  {
    name: "United Oil & Gas, USA",
    industry: "Energy",
    website: "http://www.uos.com",
    numOfEmployees: 3000,
    phone: "(650) 450-8810",
  },
  {
    name: "United Oil & Gas, Japan",
    industry: "Energy",
    website: "http://www.uos.co.jp",
    numOfEmployees: 3000,
    phone: "(650) 450-8810",
  },
  {
    name: "Cascade Technologies Ltd",
    industry: "COMPUTER_HARDWARE",
    website: "cascadetech.com",
    numOfEmployees: 200,
    phone: "+1 650-853-2048",
  },
  {
    name: "Neptune Software Solutions",
    industry: "COMPUTER_SOFTWARE",
    website: "neptunessoftware.com",
    numOfEmployees: 500,
    phone: "-",
  },
  {
    name: "Harmony Health Clinic",
    industry: "HOSPITAL_HEALTH_CARE",
    website: "harmonyhealthclinic.com",
    numOfEmployees: 150,
    phone: "4152624419",
  },
  {
    name: "DeltaCom IT Solutions",
    industry: "COMPUTER_SOFTWARE",
    website: "DELTACOM.COM",
    numOfEmployees: 200,
    phone: "+1 703-880-9000",
  },
  {
    name: "Universal Energy Solutions, UK",
    industry: "Energy",
    website: "http://www.uesolutions.co.uk",
    numOfEmployees: 35000,
    phone: "+44 191 4956213",
  },
  {
    name: "Universal Energy Solutions, Singapore",
    industry: "Energy",
    website: "http://www.uesolutions.com.sg",
    numOfEmployees: 4000,
    phone: "(650) 450-8800",
  },
  {
    name: "Universal Energy Solutions, USA",
    industry: "Energy",
    website: "http://www.uesolutions.com",
    numOfEmployees: 5000,
    phone: "(650) 450-8800",
  },
  {
    name: "Universal Energy Solutions, Japan",
    industry: "Energy",
    website: "http://www.uesolutions.co.jp",
    numOfEmployees: 4000,
    phone: "(650) 450-8800",
  },
  {
    name: "Aurora Software Systems, Inc.",
    industry: "COMPUTER_SOFTWARE",
    website: "aurorasoftsys.com",
    numOfEmployees: 75,
    phone: "+1 415-258-9037",
  },
  {
    name: "Triton International",
    industry: "SHIPPING",
    website: "triton-international.com",
    numOfEmployees: 8000,
    phone: "-",
  },
  {
    name: "Springfield General Hospital",
    industry: "HOSPITAL_HEALTH_CARE",
    website: "springfieldgen.com",
    numOfEmployees: 500,
    phone: "4152624456",
  },
  {
    name: "Astro Tech Innovations",
    industry: "COMPUTER_SOFTWARE",
    website: "AstroTechInnov.com",
    numOfEmployees: 120,
    phone: "+1 512-442-7000",
  },
  {
    name: "Solar Power & Gas, UK",
    industry: "Energy",
    website: "http://www.solarpowergas.co.uk",
    numOfEmployees: 15000,
    phone: "+44 191 4956243",
  },
  {
    name: "Solar Power & Gas, Singapore",
    industry: "Energy",
    website: "http://www.solarpowergas.com.sg",
    numOfEmployees: 2000,
    phone: "(650) 450-8820",
  },
  {
    name: "Solar Power & Gas, USA",
    industry: "Energy",
    website: "http://www.solarpowergas.com",
    numOfEmployees: 5000,
    phone: "(650) 450-8820",
  },
  {
    name: "Solar Power & Gas, Japan",
    industry: "Energy",
    website: "http://www.solarpowergas.co.jp",
    numOfEmployees: 2500,
    phone: "(650) 450-8820",
  },
];
